<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- 接口方法签名中使用的实体/模型位于 Model 层 -->
    <ProjectReference Include="..\WCS_Common\WCS_Common.csproj" />
    <ProjectReference Include="..\WCS_Model\WCS_Model.csproj" />
  </ItemGroup>

</Project>
